### ISSUE TITLE
SIGSEGV: segmentation violation

### ISSUE THREAD

**Issue by Bluscream** [Cian911/gomerge#56] opened 2022-09-25 23:12 UTC
```bash
blu@minopia:~/github/repos $ ./gomerge_list.sh
No open pull requests found for configured repositories.
+----+-------+--------------------------------+---------------------------------------+----------------------+
| PR | STATE |             TITLE              |              REPOSITORY               |       CREATED        |
+----+-------+--------------------------------+---------------------------------------+----------------------+
| #2 | open  | Update                         | xxx/xxx | 2021-03-10T05:47:18Z |
|    |       | xxx    |                                       |                      |
|    |       | xxx           |                                       |                      |
+----+-------+--------------------------------+---------------------------------------+----------------------+
? Select which Pull Requests you would like to merge. 2 | xxx                                                   2022/09/26 01:11:18 Could not merge PR #2, skipping: PUT https://api.github.com/repos/xxx/xxx/pulls/2/merge: 404 Not Found []
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x2c8f28]

goroutine 1 [running]:
github.com/cian911/go-merge/pkg/gitclient.MergePullRequest(0x4000166500, {0x4fbe70, 0x40000b0000}, {0x40000b1330, 0xb}, {0x40004d0a22, 0x19}, 0x2, {0x0, 0x0}, ...)
        /home/runner/work/gomerge/gomerge/pkg/gitclient/client.go:50 +0x198
github.com/cian911/go-merge/pkg/cli/list.NewCommand.func1(0x4000152c80, {0x40000a2a00, 0x0, 0x5})
        /home/runner/work/gomerge/gomerge/pkg/cli/list/list.go:94 +0xa00
github.com/spf13/cobra.(*Command).execute(0x4000152c80, {0x40000a29b0, 0x5, 0x5})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x66c
github.com/spf13/cobra.(*Command).ExecuteC(0x4000152a00)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x424
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:911
main.main()
        /home/runner/work/gomerge/gomerge/cmd/gomerge/main.go:22 +0x168
```

**Comment by Cian911** [comment] 2022-09-26 09:41
Hi @Bluscream, thanks so much for the report. Just to ask what might be the obvious for clarity:

1. Are you running the same script you have above as you have documented in https://github.com/Cian911/gomerge/issues/55? 

2. Are you merging or approving the selected PRs?

3. When exactly does the segfault occur, it looks to be after you've selected and choose to merge/approve the selected repos, is that correct?

4. Do you have access to all access to all configured repos? Are any archived?

**Comment by Bluscream** [comment] 2022-09-26 14:52
> 1. Are you running the same script you have above as you have documented in [[Tutorial] How to use this on all your repos #55](https://github.com/Cian911/gomerge/issues/55)?

Yes

> 2. Are you merging or approving the selected PRs?

I want to merge first, and then close all remaining unmergables

> 3. When exactly does the segfault occur, it looks to be after you've selected and choose to merge/approve the selected repos, is that correct?

Correct

> 4. Do you have access to all access to all configured repos? Are any archived?

Some are archived and atleast one in there is DMCA'ed, and to some i might not have push permissions

**Comment by Cian911** [comment] 2022-09-26 15:05
> Some are archived and atleast one in there is DMCA'ed, and to some i might not have push permissions

Are you trying to merge PRs from any of these?

> what i also found out was that even the github web frontend doesn't like batch-merging. When i merge two PRs too close together (within a one or two seconds from eachother, it errors out and i have to reload the second PR and try merging it again) so maybe a sleep inbetween merges would be useful

Yes I've encountered this before, though in this case the fact the PR is un-mergable for a brief time I catch this as an error already so this I don't think is the source of the segfault. This happens because after one PR is merged, others in the repo will likely need to be rebased (depending on the files changed), I think I might have mentioned something like this before in a previous issue you created ;) https://github.com/Cian911/gomerge/issues/40#issuecomment-1165696763

Also thanks for the response, I will try and replicate the issue myself first and If I run into any issues I'll reach out to you for more info. And thanks again for the issue! Love the fact you're actively and regularly using `gomerge` and you're getting value out of it.

**Comment by Cian911** [comment] 2022-09-26 15:15
> they might be under all the other repos, and picking them out everytime i regenerate is not really a viable option. can't it just skip erroring operations as it's supposed to?

Yes it should, the reason I ask is I don't think I've tested against either scenario, I have a suspicion the problem is here, but I will test to see ;) 

Do you think you could link me to the DMCA'd repo you mentioned?

**Comment by Bluscream** [comment] 2022-09-26 15:18
> Do you think you could link me to the DMCA'd repo you mentioned?

https://github.com/Bluscream/DayZ-Private
```
451 {"message": "Repository access blocked", "block": {"reason": "dmca", "created_at": "2014-05-30T19:18:22Z", "html_url": "https://github.com/github/dmca/blob/master/2014/2014-05-30-Bec.md"}}
```

**Comment by Cian911** [comment] 2022-09-28 21:45
@Bluscream I _think_ I may have found the source of the issue in the `close` operation. I wasn't handling the proceeding step after an error occurred correctly. I also added a `delay` flag too. You can checkout the PR here: https://github.com/Cian911/gomerge/pull/57

Do you think you can checkout my branch to test against your use case for me? Instructions to build and run from source are all in the project `Makefile`.

**Comment by Cian911** [comment] 2022-10-02 13:42
Hi @Bluscream I've merged the PR above as I'd like to get a new release out with this fix, In the meantime I will leave this open for you if you want to let me know if you encounter this issue again, but I think it should be solved. Thanks!

**Comment by Bluscream** [comment] 2022-10-02 21:45
Oh yes, sorry for the delay. I was planning to do it next time i'm on my PC but that next time never happend. Will keep you posted

**Comment by Cian911** [comment] 2022-10-16 11:47
Gona close this for now - If it crops up again I can re-open this issue. Thanks again!

**Closed by Cian911** 2022-10-16 11:47 UTC
Labels: bug, wip
